# Generated by Django 3.0.5 on 2021-06-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confcode', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='confcode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ConfCode'),
        ),
    ]
