# Generated by Django 3.0.5 on 2021-06-19 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210619_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confcode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='confcode',
        ),
        migrations.AddField(
            model_name='confcode',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confcode',
            name='confcode',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
