# Generated by Django 3.0.5 on 2021-06-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_myuser_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
    ]
