# Generated by Django 3.0.5 on 2021-06-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210619_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confcode',
            name='user',
        ),
        migrations.AddField(
            model_name='confcode',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confcode',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
