# Generated by Django 3.0.5 on 2021-06-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210613_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
